### ISSUE TITLE
Каждую отправку письма выполняется считывание конфигурации для почти.

### ISSUE THREAD

**Issue by kudryaA** [pyrih/NCTaskManager#3]

**Comment by kudryaA** [comment]
Нужно вынести считывание конфига в utility и перенести создание сессии почты в конструктор. Тогда сессия будет создана только один раз и не будет создаваться каждый раз при отправке.

**Comment by pyrih** [comment]
вынес считывание  properties в статический метод в util классе, перенес создание сессии в конструктор класса
