### ISSUE TITLE
Нету смысла спрашивать у пользователя за активность таски. Это лучше убрать.

### ISSUE THREAD

**Issue by kudryaA** [pyrih/NCTaskManager#7]

**Comment by pyrih** [comment]
убрал запрос на ввод статуса активности задачи при добавлении её в менеджер. Оставил при редактировании задачи, так как есть вероятность того что на какой-то период нужно будет сделать задачу неактивной (например уехал в отпуск, нужно деактивировать таски которые не будет возможности выполнять. в следствие чего нотификации тоже не отправляются для неактивных тасок)
